from glob import glob
import os
import os.path

libs = ['rt']
ccflags = ['-O3', '-DNDEBUG', '-Werror', '-Wall']
cpppath = ['../..']

source_files = glob('*.c')
source_files += ['../../libqform/libqform.a']
source_files += ['../../liboptarith/liboptarith.a']

# Check for PARI.
hasPari = os.path.exists('/usr/include/pari/pari.h') or \
          os.path.exists('/usr/local/include/pari/pari.h')

if not hasPari:
    ccflags += ['-DNO_PARI']
else:
    if os.path.isfile('/usr/local/lib/libpari.a'):
        source_files.append('/usr/local/lib/libpari.a')
    elif os.path.isfile('/usr/lib/libpari.a'):
        source_files.append('/usr/lib/libpari.a')
    else:
        libs.append('pari')

# libgmp
if os.path.isfile('/usr/local/lib/libgmp.a'):
    source_files.append('/usr/local/lib/libgmp.a')
elif os.path.isfile('/usr/lib/libgmp.a'):
    source_files.append('/usr/lib/libgmp.a')
else:
    libs.append('gmp')

Program(target='time_qforms',
        source=source_files,
        CPPPATH=cpppath,
        CCFLAGS=ccflags,
        LIBS=libs)
	
